server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dijital_kart_db?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: dijitalKartSecretKey123456789
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: http://localhost:3000 